project_id = "bomjibcivwxbcwfmkrnv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
buckets = []

[auth]
enabled = true
additional_redirect_urls = ["https://bomjibcivwxbcwfmkrnv.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
# Set OTP expiry to 1 minute (60 seconds) for better security
otp_expiry = 60

[auth.password]
# Enable password breach detection
breach_detection = true

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = false