project_id = "bomjibcivwxbcwfmkrnv"

[auth]
enabled = true

[auth.email]
# Set OTP expiry to 1 minute (60 seconds) for better security
otp_expiry = 60

[auth.password]
# Enable password breach detection
breach_detection = true

[functions.send-invitation-email]
verify_jwt = false