project_id = "bomjibcivwxbcwfmkrnv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[edge_runtime]
enabled = true
port = 54328

[functions.process-meeting-audio]
verify_jwt = true

[functions.assemblyai-token]
verify_jwt = true

[functions.extract-acts-incremental]
verify_jwt = true

[functions.trial-reminder]
verify_jwt = false

[functions.security-incident-response]
verify_jwt = true

[functions.debug-keys]
verify_jwt = false

[functions.test-api-keys]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-custom]
verify_jwt = false

# Week 2: Google Calendar Integration
[functions.calendar-google-auth]
verify_jwt = false

[functions.calendar-google-sync]
verify_jwt = true

[functions.create-google-calendar-event]
verify_jwt = true

# Week 2: Vision Framework
[functions.generate-weekly-affirmation]
verify_jwt = true

# Week 2: Smart Scheduling
[functions.optimize-schedule]
verify_jwt = true

# Week 3: AssemblyAI Webhook
[functions.assemblyai-webhook]
verify_jwt = false
